
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: "ELEC4630 AI Learning Journey"
description: "Documenting my exploration of Computer Vision and Deep Learning at UQ"

author: Isaac Johan Ziebarth

# Social and contact links
github_username: Zyzzbarth333
linkedin_username: isaacjohanziebarth
email: IJZiebarth@outlook.com.au
studentemail: i.ziebarth@student.uq.edu.au

# Set this to true to get LaTeX math equation support
use_math: true

# Add your Google Analytics ID here if you have one and want to use it
google_analytics:

image: /images/test1.jpg

# Theme settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-github-metadata

# Header pages - controls which pages appear in the navigation
header_pages:
  - about.md

# Titles from headings settings
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

# URL settings
# If you change to a custom domain, set it here
# baseurl: ""
# url: "https://yourdomain.com"

# Build settings
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge

highlighter: rouge

# Default layout for posts
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: Isaac Johan Ziebarth

# To enable excerpts on the home page
show_excerpts: true
# To enable excerpts on the home page
show_excerpts: true
